### ISSUE TITLE
Error on the "All Courses" button 

### ISSUE THREAD

**Issue by NelsonDiasFCCN** [up2university/docker-moodle#109] opened 2018-11-30 15:18 UTC
The **"All Courses"** button on the learning platform doesn't work.
Error message:
**_"Not Found
The requested URL /title was not found on this server.

Apache/2.4.7 (Ubuntu) Server at learn.up2university.eu Port 443"_**

Please see the screenshot below

![screenshot 2018-11-30 at 15 06 47](https://user-images.githubusercontent.com/16823022/49297057-c4074680-f4b1-11e8-9896-40a133db8a82.png)

**Comment by michzimny** [comment] 2018-11-30 16:02
Closing as duplicate of #93

**Closed by michzimny** 2018-11-30 16:02 UTC
