### ISSUE TITLE
Not be able to add activities to course moodle as a teacher

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/docker-moodle#116] opened 2018-12-17 11:13 UTC
Hi everyone!

I found this problem trying to add one activity as a teacher role.

**First of all,** as a manager, it works fine. I edit course as a manager and then I add an activity.
In this case I have a complete list of activities.

You can see the list in the image.

![add_activities_ok_v001](https://user-images.githubusercontent.com/11814769/50083490-499a2e80-01f4-11e9-8e03-b27697840013.png)

But if I change to **teacher role**. The list of activities is incomplete.

As you can see the next image.

![add_activities_ok_v002](https://user-images.githubusercontent.com/11814769/50083578-8ebe6080-01f4-11e9-8e8d-e29a42a0989c.png)

It happens in both instance of moodle.

https://learn.test.up2university.eu

&&

https://learn.up2university.eu

**It is urgent,** because my group of teachers need access to create their own content.

**Comment by msbachler** [comment] 2018-12-17 14:00
Duplicate of #106.

**Closed by msbachler** 2018-12-17 14:00 UTC
