### ISSUE TITLE
theme_fordson showonlycustomactivities must be disabled

### ISSUE THREAD

**Issue by elinara** [up2university/docker-moodle#106] opened 2018-11-22 17:20 UTC
The setting showonlycustomactivities must be disabled because otherwise the non administrative user can not create a new activity.

**Comment by michzimny** [comment] 2018-12-17 15:33
@athird, @msbachler, from #116 it seems that the issue is blocking some users. Shall we make quick test of merged changes and deploy the latest version to all instances?

@ivanoterouvigo, are your teachers using the production instance?

**Comment by ivanoterouvigo** [comment] 2018-12-17 15:48
Yes, I began to work with them in production instance. But we are at the beginning.
I would like to give them the oportunity of create content in hide mode.
But teacher role didn't let them to work like this

**Comment by michzimny** [comment] 2018-12-17 16:33
OK. 
@athird, @msbachler, shall we schedule deployment to the pedagogy and then production instances?

**Comment by michzimny** [comment] 2018-12-18 19:32
If we could do this outside of working hours and book some additional time to solve things if anything occurs after deployment, then any day is fine. If not, then I need to check with pilot countries as some activities with teachers are ongoing.

I'm afraid I will not find enough time till the end of the month to participate in the technical side.

**Comment by michzimny** [comment] 2018-12-18 21:16
@athird, however, in case of blockers as #116, I think we need to fix them ASAP. Either by deployment or a manual fix.

**Comment by michzimny** [comment] 2019-01-03 14:58
@athird, @msbachler, this issue is blocking users. Could we schedule deployments of the fix?

I think it could be done at any time, if before 7th January. Otherwise, we need to agree on a proper time.

**Comment by athird** [comment] 2019-01-06 21:17
@michzimny I've manually set the right configurations on production and pedagogy; I didn't want to risk stability by redeploying possibly other new stuff at the same time. Same for #82 and #93.

**Closed** 2019-01-29 09:24 UTC
Labels: critical, production-update-critical
